/**
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.msl.ui.AbstractMSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class MSLUiModule extends AbstractMSLUiModule {
}
