/**
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.msl.MSLRuntimeModule;
import org.xtext.msl.MSLStandaloneSetup;
import org.xtext.msl.ide.MSLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MSLIdeSetup extends MSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MSLRuntimeModule _mSLRuntimeModule = new MSLRuntimeModule();
    MSLIdeModule _mSLIdeModule = new MSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mSLRuntimeModule, _mSLIdeModule));
  }
}
