/**
 * generated by Xtext 2.14.0
 */
package org.xtext.msl.mSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.msl.mSL.AbstractSystem;
import org.xtext.msl.mSL.MSLPackage;
import org.xtext.msl.mSL.SystemBinding;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Binding</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.msl.mSL.impl.SystemBindingImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.impl.SystemBindingImpl#getAbsSys <em>Abs Sys</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SystemBindingImpl extends MinimalEObjectImpl.Container implements SystemBinding
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAbsSys() <em>Abs Sys</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbsSys()
   * @generated
   * @ordered
   */
  protected AbstractSystem absSys;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemBindingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MSLPackage.Literals.SYSTEM_BINDING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MSLPackage.SYSTEM_BINDING__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractSystem getAbsSys()
  {
    if (absSys != null && absSys.eIsProxy())
    {
      InternalEObject oldAbsSys = (InternalEObject)absSys;
      absSys = (AbstractSystem)eResolveProxy(oldAbsSys);
      if (absSys != oldAbsSys)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MSLPackage.SYSTEM_BINDING__ABS_SYS, oldAbsSys, absSys));
      }
    }
    return absSys;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractSystem basicGetAbsSys()
  {
    return absSys;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAbsSys(AbstractSystem newAbsSys)
  {
    AbstractSystem oldAbsSys = absSys;
    absSys = newAbsSys;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MSLPackage.SYSTEM_BINDING__ABS_SYS, oldAbsSys, absSys));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MSLPackage.SYSTEM_BINDING__NAME:
        return getName();
      case MSLPackage.SYSTEM_BINDING__ABS_SYS:
        if (resolve) return getAbsSys();
        return basicGetAbsSys();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MSLPackage.SYSTEM_BINDING__NAME:
        setName((String)newValue);
        return;
      case MSLPackage.SYSTEM_BINDING__ABS_SYS:
        setAbsSys((AbstractSystem)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MSLPackage.SYSTEM_BINDING__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MSLPackage.SYSTEM_BINDING__ABS_SYS:
        setAbsSys((AbstractSystem)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MSLPackage.SYSTEM_BINDING__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MSLPackage.SYSTEM_BINDING__ABS_SYS:
        return absSys != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SystemBindingImpl
