/*
 * generated by Xtext 2.12.0
 */
package org.xtext.msl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.msl.ui.internal.MslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MslActivator.getInstance().getInjector(MslActivator.ORG_XTEXT_MSL_MSL);
	}
	
}
