/**
 * generated by Xtext 2.16.0
 */
package org.xtext.msl.mSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.msl.mSL.ComponentName#getComponent <em>Component</em>}</li>
 * </ul>
 *
 * @see org.xtext.msl.mSL.MSLPackage#getComponentName()
 * @model
 * @generated
 */
public interface ComponentName extends EObject
{
  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(ComponentInstance)
   * @see org.xtext.msl.mSL.MSLPackage#getComponentName_Component()
   * @model
   * @generated
   */
  ComponentInstance getComponent();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.ComponentName#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(ComponentInstance value);

} // ComponentName
