/**
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.mSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.msl.mSL.ConcreteGroup#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.ConcreteGroup#getAbstractGroups <em>Abstract Groups</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.ConcreteGroup#getManSys <em>Man Sys</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.ConcreteGroup#getManGrp <em>Man Grp</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.ConcreteGroup#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup()
 * @model
 * @generated
 */
public interface ConcreteGroup extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.ConcreteGroup#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Abstract Groups</b></em>' reference list.
   * The list contents are of type {@link org.xtext.msl.mSL.GroupBinding}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract Groups</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Groups</em>' reference list.
   * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup_AbstractGroups()
   * @model
   * @generated
   */
  EList<GroupBinding> getAbstractGroups();

  /**
   * Returns the value of the '<em><b>Man Sys</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Man Sys</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Man Sys</em>' reference.
   * @see #setManSys(ConcreteSystem)
   * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup_ManSys()
   * @model
   * @generated
   */
  ConcreteSystem getManSys();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.ConcreteGroup#getManSys <em>Man Sys</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Man Sys</em>' reference.
   * @see #getManSys()
   * @generated
   */
  void setManSys(ConcreteSystem value);

  /**
   * Returns the value of the '<em><b>Man Grp</b></em>' reference list.
   * The list contents are of type {@link org.xtext.msl.mSL.ConcreteGroup}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Man Grp</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Man Grp</em>' reference list.
   * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup_ManGrp()
   * @model
   * @generated
   */
  EList<ConcreteGroup> getManGrp();

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.msl.mSL.ComponentInstance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.xtext.msl.mSL.MSLPackage#getConcreteGroup_Components()
   * @model containment="true"
   * @generated
   */
  EList<ComponentInstance> getComponents();

} // ConcreteGroup
