/**
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.mSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.msl.mSL.Pattern#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.Pattern#getAbsPattern <em>Abs Pattern</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.Pattern#getManagedSystems <em>Managed Systems</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.Pattern#getGroups <em>Groups</em>}</li>
 * </ul>
 *
 * @see org.xtext.msl.mSL.MSLPackage#getPattern()
 * @model
 * @generated
 */
public interface Pattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.msl.mSL.MSLPackage#getPattern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.Pattern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Abs Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abs Pattern</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abs Pattern</em>' reference.
   * @see #setAbsPattern(AbstractPattern)
   * @see org.xtext.msl.mSL.MSLPackage#getPattern_AbsPattern()
   * @model
   * @generated
   */
  AbstractPattern getAbsPattern();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.Pattern#getAbsPattern <em>Abs Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abs Pattern</em>' reference.
   * @see #getAbsPattern()
   * @generated
   */
  void setAbsPattern(AbstractPattern value);

  /**
   * Returns the value of the '<em><b>Managed Systems</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.msl.mSL.SystemBinding}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Managed Systems</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Managed Systems</em>' containment reference list.
   * @see org.xtext.msl.mSL.MSLPackage#getPattern_ManagedSystems()
   * @model containment="true"
   * @generated
   */
  EList<SystemBinding> getManagedSystems();

  /**
   * Returns the value of the '<em><b>Groups</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.msl.mSL.GroupBinding}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Groups</em>' containment reference list.
   * @see org.xtext.msl.mSL.MSLPackage#getPattern_Groups()
   * @model containment="true"
   * @generated
   */
  EList<GroupBinding> getGroups();

} // Pattern
