/**
 * generated by Xtext 2.15.0
 */
package org.xtext.msl.mSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.msl.mSL.SystemBinding#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.msl.mSL.SystemBinding#getAbsSys <em>Abs Sys</em>}</li>
 * </ul>
 *
 * @see org.xtext.msl.mSL.MSLPackage#getSystemBinding()
 * @model
 * @generated
 */
public interface SystemBinding extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.msl.mSL.MSLPackage#getSystemBinding_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.SystemBinding#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Abs Sys</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abs Sys</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abs Sys</em>' reference.
   * @see #setAbsSys(AbstractSystem)
   * @see org.xtext.msl.mSL.MSLPackage#getSystemBinding_AbsSys()
   * @model
   * @generated
   */
  AbstractSystem getAbsSys();

  /**
   * Sets the value of the '{@link org.xtext.msl.mSL.SystemBinding#getAbsSys <em>Abs Sys</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abs Sys</em>' reference.
   * @see #getAbsSys()
   * @generated
   */
  void setAbsSys(AbstractSystem value);

} // SystemBinding
