/*
 * generated by Xtext 2.13.0
 */
package org.xtext.msl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MSLStandaloneSetup extends MSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
