/**
 * generated by Xtext 2.13.0
 */
package org.xtext.msl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MSLStandaloneSetup extends MSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
