/*
 * generated by Xtext 2.12.0
 */
package org.xtext.msl.ide.contentassist.antlr;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.msl.ide.contentassist.antlr.internal.InternalMSLParser;
import org.xtext.msl.services.MSLGrammarAccess;

import com.google.inject.Inject;

public class MSLParser extends AbstractContentAssistParser {

	@Inject
	private MSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMSLParser createParser() {
		InternalMSLParser result = new InternalMSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSpecificationAccess().getGroup(), "rule__Specification__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getAbstractPatternAccess().getGroup(), "rule__AbstractPattern__Group__0");
					put(grammarAccess.getAbstractSystemAccess().getGroup(), "rule__AbstractSystem__Group__0");
					put(grammarAccess.getGroupDefAccess().getGroup(), "rule__GroupDef__Group__0");
					put(grammarAccess.getGroupDefAccess().getGroup_1(), "rule__GroupDef__Group_1__0");
					put(grammarAccess.getAbstractGroupAccess().getGroup(), "rule__AbstractGroup__Group__0");
					put(grammarAccess.getAbstractGroupAccess().getGroup_3(), "rule__AbstractGroup__Group_3__0");
					put(grammarAccess.getAbstractGroupAccess().getGroup_4(), "rule__AbstractGroup__Group_4__0");
					put(grammarAccess.getAbstractGroupAccess().getGroup_4_2(), "rule__AbstractGroup__Group_4_2__0");
					put(grammarAccess.getAbstractGroupAccess().getGroup_7(), "rule__AbstractGroup__Group_7__0");
					put(grammarAccess.getAbstractInteractionAccess().getGroup(), "rule__AbstractInteraction__Group__0");
					put(grammarAccess.getAbstractInteractionAccess().getGroup_4(), "rule__AbstractInteraction__Group_4__0");
					put(grammarAccess.getSystemBindingAccess().getGroup(), "rule__SystemBinding__Group__0");
					put(grammarAccess.getGroupBindingAccess().getGroup(), "rule__GroupBinding__Group__0");
					put(grammarAccess.getPatternAccess().getGroup(), "rule__Pattern__Group__0");
					put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
					put(grammarAccess.getConfigurationAccess().getGroup_3(), "rule__Configuration__Group_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_3_1(), "rule__Configuration__Group_3_1__0");
					put(grammarAccess.getConcreteSystemAccess().getGroup(), "rule__ConcreteSystem__Group__0");
					put(grammarAccess.getConcreteSystemAccess().getGroup_2(), "rule__ConcreteSystem__Group_2__0");
					put(grammarAccess.getConcreteSystemAccess().getGroup_2_1(), "rule__ConcreteSystem__Group_2_1__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup(), "rule__ConcreteGroup__Group__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_2(), "rule__ConcreteGroup__Group_2__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_2_1(), "rule__ConcreteGroup__Group_2_1__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_4(), "rule__ConcreteGroup__Group_4__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_5(), "rule__ConcreteGroup__Group_5__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_5_2(), "rule__ConcreteGroup__Group_5_2__0");
					put(grammarAccess.getConcreteGroupAccess().getGroup_8(), "rule__ConcreteGroup__Group_8__0");
					put(grammarAccess.getComponentInstanceAccess().getGroup(), "rule__ComponentInstance__Group__0");
					put(grammarAccess.getInteractionAccess().getGroup(), "rule__Interaction__Group__0");
					put(grammarAccess.getSpecificationAccess().getImportsAssignment_0(), "rule__Specification__ImportsAssignment_0");
					put(grammarAccess.getSpecificationAccess().getAbsPatternAssignment_1(), "rule__Specification__AbsPatternAssignment_1");
					put(grammarAccess.getSpecificationAccess().getPatternAssignment_2(), "rule__Specification__PatternAssignment_2");
					put(grammarAccess.getSpecificationAccess().getConfigurationAssignment_3(), "rule__Specification__ConfigurationAssignment_3");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getAbstractPatternAccess().getNameAssignment_2(), "rule__AbstractPattern__NameAssignment_2");
					put(grammarAccess.getAbstractPatternAccess().getManagedSystemsAssignment_4(), "rule__AbstractPattern__ManagedSystemsAssignment_4");
					put(grammarAccess.getAbstractPatternAccess().getAbstractGroupsAssignment_5(), "rule__AbstractPattern__AbstractGroupsAssignment_5");
					put(grammarAccess.getAbstractPatternAccess().getInteractionsAssignment_6(), "rule__AbstractPattern__InteractionsAssignment_6");
					put(grammarAccess.getAbstractSystemAccess().getNameAssignment_1(), "rule__AbstractSystem__NameAssignment_1");
					put(grammarAccess.getAbstractComponentAccess().getNameAssignment(), "rule__AbstractComponent__NameAssignment");
					put(grammarAccess.getGroupDefAccess().getGrpAssignment_0(), "rule__GroupDef__GrpAssignment_0");
					put(grammarAccess.getGroupDefAccess().getMultAssignment_1_1(), "rule__GroupDef__MultAssignment_1_1");
					put(grammarAccess.getAbstractGroupAccess().getNameAssignment_1(), "rule__AbstractGroup__NameAssignment_1");
					put(grammarAccess.getAbstractGroupAccess().getManSysAssignment_3_1(), "rule__AbstractGroup__ManSysAssignment_3_1");
					put(grammarAccess.getAbstractGroupAccess().getManGrpAssignment_4_1(), "rule__AbstractGroup__ManGrpAssignment_4_1");
					put(grammarAccess.getAbstractGroupAccess().getManGrpAssignment_4_2_1(), "rule__AbstractGroup__ManGrpAssignment_4_2_1");
					put(grammarAccess.getAbstractGroupAccess().getComponentsAssignment_6(), "rule__AbstractGroup__ComponentsAssignment_6");
					put(grammarAccess.getAbstractGroupAccess().getComponentsAssignment_7_1(), "rule__AbstractGroup__ComponentsAssignment_7_1");
					put(grammarAccess.getAbstractInteractionAccess().getStartAssignment_1(), "rule__AbstractInteraction__StartAssignment_1");
					put(grammarAccess.getAbstractInteractionAccess().getEndAssignment_3(), "rule__AbstractInteraction__EndAssignment_3");
					put(grammarAccess.getAbstractInteractionAccess().getLowAssignment_4_1(), "rule__AbstractInteraction__LowAssignment_4_1");
					put(grammarAccess.getAbstractInteractionAccess().getHighAssignment_4_3(), "rule__AbstractInteraction__HighAssignment_4_3");
					put(grammarAccess.getAbstractComponentNameAccess().getTypeAssignment(), "rule__AbstractComponentName__TypeAssignment");
					put(grammarAccess.getSystemBindingAccess().getNameAssignment_1(), "rule__SystemBinding__NameAssignment_1");
					put(grammarAccess.getSystemBindingAccess().getAbsSysAssignment_3(), "rule__SystemBinding__AbsSysAssignment_3");
					put(grammarAccess.getGroupBindingAccess().getNameAssignment_1(), "rule__GroupBinding__NameAssignment_1");
					put(grammarAccess.getGroupBindingAccess().getAbsGroupAssignment_3(), "rule__GroupBinding__AbsGroupAssignment_3");
					put(grammarAccess.getPatternAccess().getNameAssignment_2(), "rule__Pattern__NameAssignment_2");
					put(grammarAccess.getPatternAccess().getAbsPatternAssignment_4(), "rule__Pattern__AbsPatternAssignment_4");
					put(grammarAccess.getPatternAccess().getManagedSystemsAssignment_6(), "rule__Pattern__ManagedSystemsAssignment_6");
					put(grammarAccess.getPatternAccess().getGroupsAssignment_7(), "rule__Pattern__GroupsAssignment_7");
					put(grammarAccess.getConfigurationAccess().getNameAssignment_1(), "rule__Configuration__NameAssignment_1");
					put(grammarAccess.getConfigurationAccess().getPatternAssignment_3_0(), "rule__Configuration__PatternAssignment_3_0");
					put(grammarAccess.getConfigurationAccess().getPatternAssignment_3_1_1(), "rule__Configuration__PatternAssignment_3_1_1");
					put(grammarAccess.getConfigurationAccess().getConcreteSystemsAssignment_5(), "rule__Configuration__ConcreteSystemsAssignment_5");
					put(grammarAccess.getConfigurationAccess().getConcreteGroupsAssignment_6(), "rule__Configuration__ConcreteGroupsAssignment_6");
					put(grammarAccess.getConfigurationAccess().getConcreteInteractionsAssignment_7(), "rule__Configuration__ConcreteInteractionsAssignment_7");
					put(grammarAccess.getConcreteSystemAccess().getNameAssignment_0(), "rule__ConcreteSystem__NameAssignment_0");
					put(grammarAccess.getConcreteSystemAccess().getBindingsAssignment_2_0(), "rule__ConcreteSystem__BindingsAssignment_2_0");
					put(grammarAccess.getConcreteSystemAccess().getBindingsAssignment_2_1_1(), "rule__ConcreteSystem__BindingsAssignment_2_1_1");
					put(grammarAccess.getConcreteGroupAccess().getNameAssignment_0(), "rule__ConcreteGroup__NameAssignment_0");
					put(grammarAccess.getConcreteGroupAccess().getAbstractGroupsAssignment_2_0(), "rule__ConcreteGroup__AbstractGroupsAssignment_2_0");
					put(grammarAccess.getConcreteGroupAccess().getAbstractGroupsAssignment_2_1_1(), "rule__ConcreteGroup__AbstractGroupsAssignment_2_1_1");
					put(grammarAccess.getConcreteGroupAccess().getManSysAssignment_4_1(), "rule__ConcreteGroup__ManSysAssignment_4_1");
					put(grammarAccess.getConcreteGroupAccess().getManGrpAssignment_5_1(), "rule__ConcreteGroup__ManGrpAssignment_5_1");
					put(grammarAccess.getConcreteGroupAccess().getManGrpAssignment_5_2_1(), "rule__ConcreteGroup__ManGrpAssignment_5_2_1");
					put(grammarAccess.getConcreteGroupAccess().getComponentsAssignment_7(), "rule__ConcreteGroup__ComponentsAssignment_7");
					put(grammarAccess.getConcreteGroupAccess().getComponentsAssignment_8_1(), "rule__ConcreteGroup__ComponentsAssignment_8_1");
					put(grammarAccess.getComponentInstanceAccess().getNameAssignment_0(), "rule__ComponentInstance__NameAssignment_0");
					put(grammarAccess.getComponentInstanceAccess().getTypeAssignment_2(), "rule__ComponentInstance__TypeAssignment_2");
					put(grammarAccess.getInteractionAccess().getStartAssignment_0(), "rule__Interaction__StartAssignment_0");
					put(grammarAccess.getInteractionAccess().getEndAssignment_2(), "rule__Interaction__EndAssignment_2");
					put(grammarAccess.getComponentNameAccess().getComponentAssignment(), "rule__ComponentName__ComponentAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
