/*
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMSLScopeProvider extends DelegatingScopeProvider {
}
