/*
 * generated by Xtext 2.13.0
 */
package org.xtext.msl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.msl.MSLRuntimeModule
import org.xtext.msl.MSLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MSLIdeSetup extends MSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MSLRuntimeModule, new MSLIdeModule))
	}
	
}
